<a href="https://colab.research.google.com/github/tomonari-masada/course2025-intro2ml/blob/main/05_NumPy_1_ipynb_%E3%81%AE%E3%82%B3%E3%83%94%E3%83%BC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy入門 (1)

* NumPyを説明する前に・・・

## モジュール、パッケージ、ライブラリ
* 参考資料
  * https://zenn.dev/delacroix/articles/e3f62ca001deb0


* モジュール
  * Pythonのファイル(.pyファイル)のこと。
  * `import`文で.pyファイルをインポートすることで、その.pyファイルの中の関数やクラスを使用することができるようになる。
* パッケージ
  * モジュールを複数集めたものです。
  * つまり .pyファイルを複数置いてあるフォルダのようなもの。
  * 言葉としては、次の「ライブラリ」と区別せずに使われることもある。
    * Python Package Index https://pypi.org/
* ライブラリ
  * 複数のパッケージからなるPythonコードの集合体。
  * 標準ライブラリと外部ライブラリがある。
  * 標準ライブラリは、Pythonにはじめからくっついてくるライブラリ。

## mathモジュール
* Pythonでは数学的な処理をするためのモジュールがいくつか用意されている。
  * https://docs.python.org/ja/3.13/library/numeric.html

In [3]:
import math

In [4]:
a = 2.0

In [5]:
b = math.sqrt(a)
print(a, b)

2.0 1.4142135623730951


In [6]:
c = math.exp(a)
print(a, c)

2.0 7.38905609893065


In [7]:
d = math.sin(a)
print(a, d)

2.0 0.9092974268256817


# NumPyライブラリ

* ベクトルや行列を扱える（他にも様々な機能がある）
 * ベクトルどうしの内積
 * 行列とベクトルの積
 * 行列と行列の積
 * 逆行列

* ndarrayという独自のデータ構造を使う
 * ちゃんとコードを書けば高速（ちゃんと書かないと遅い・・・）


## NumPyの配列(ndarray)の作り方

### Pythonのリストから作る

In [10]:
import numpy as np

* 一次元配列
  * ベクトルを使いたい時。

In [12]:
print([-2.0, 1.0, 3.0])

[-2.0, 1.0, 3.0]


In [11]:
a = np.array([-2.0, 1.0, 3.0])
print(a)

[-2.  1.  3.]


* 二次元配列
  * 行列を使いたいとき。

In [15]:
b = np.array([[1,2,3], [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


* 転置

In [16]:
print(a.T)

[-2.  1.  3.]


In [17]:
print(b.T)

[[1 4]
 [2 5]
 [3 6]]


### ndarrayの演算

In [18]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [19]:
print(a * 3)

[3 6 9]


In [20]:
c = a * 3
print(c)

[3 6 9]


In [21]:
b = np.array([2, 2, 0])
print(b)

[2 2 0]


In [23]:
print(a)
print(b)
print(a + b)

[1 2 3]
[2 2 0]
[3 4 3]


In [24]:
print(a * b)

[2 4 0]


In [25]:
print(a / b) #エラーが出る（どんなエラー？）

[0.5 1.  inf]


<ipython-input-25-3d500bdfd3c9>:1: RuntimeWarning: divide by zero encountered in divide
  print(a / b) #エラーが出る（どんなエラー？）


* ベクトルの内積

In [26]:
print(a)
print(b)
print(np.dot(a, b))

[1 2 3]
[2 2 0]
6


* インデックスで要素にアクセスできる。
  * リストやタプルと同じ。

In [30]:
a[2]

np.int64(3)

In [27]:
s = 0
for i in range(len(a)):
  s += a[i] * b[i]
print(s)

6


### ndarrayの属性

In [31]:
a = np.array([-2.0, 1.0, 3.0])
b = np.array([[1, 2, 3], [4, 5, 6]])

* 配列自体のデータ型

In [32]:
print(type(a))

<class 'numpy.ndarray'>


* 配列の要素のデータ型
  * つまり配列の中身のデータ型

In [33]:
print(a.dtype)

float64


* 配列のサイズ

In [34]:
print(a.size, b.size)

3 6


* 配列の要素のサイズ

In [ ]:
print(a.itemsize, b.itemsize)

* 次元数

In [36]:
print(b)

[[1 2 3]
 [4 5 6]]


In [35]:
print(a.ndim, b.ndim)

1 2


* 形状

In [39]:
print(b)

[[1 2 3]
 [4 5 6]]


In [37]:
print(a.shape, b.shape)

(3,) (2, 3)


### ndarrayの作り方のいろいろ

In [43]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [42]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [44]:
for i in range(0, 10, 2):
  print(i)

0
2
4
6
8


In [45]:
b = np.arange(0, 10, 2)
print(b)

[0 2 4 6 8]


In [51]:
x = np.linspace(0, 10, 21) #0以上10以下を10等分
print(x)

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10. ]


* 配列を乱数で埋める

In [57]:
print(np.random.randn()) #正規乱数

-0.9382805383588977


In [61]:
a = np.random.randn(2, 3) # 2行3列
print(a)

[[-1.28087258  1.7884448  -0.82961957]
 [ 0.74255755  1.30085148 -0.1446068 ]]


In [62]:
b = np.random.randn(3, 4)
print(b)

[[-0.55773939  1.5873045  -1.10692863  0.74778348]
 [-0.14307037 -0.547767   -1.21012789  1.61278433]
 [-1.21808383 -0.44246876 -0.5977189  -0.39839748]]


* 行列の掛け算

In [65]:
print(np.dot(a, b))

[[ 1.4690658  -2.64570511 -0.2505331   2.25707873]
 [-0.42412369  0.53008542 -2.30972065  2.71087614]]


* 次のセルはエラーになる。
  * なぜ？

In [66]:
print(np.dot(b, a))

ValueError: shapes (3,4) and (2,3) not aligned: 4 (dim 1) != 2 (dim 0)

* 配列をゼロやその他の数値で埋める

In [67]:
a = np.zeros((3,3)) #()で囲む必要あり
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [68]:
b = np.ones((3,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


* 問：次のセルの出力結果がなぜそうなるか、説明してみよう。

In [69]:
print(np.dot(b, b))

[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]


In [73]:
c = np.full((6,23), -2.3241212)
print(c)

[[-2.3241212 -2.3241212 -2.3241212 -2.3241212 -2.3241212 -2.3241212
  -2.3241212 -2.3241212 -2.3241212 -2.3241212 -2.3241212 -2.3241212
  -2.3241212 -2.3241212 -2.3241212 -2.3241212 -2.3241212 -2.3241212
  -2.3241212 -2.3241212 -2.3241212 -2.3241212 -2.3241212]
 [-2.3241212 -2.3241212 -2.3241212 -2.3241212 -2.3241212 -2.3241212
  -2.3241212 -2.3241212 -2.3241212 -2.3241212 -2.3241212 -2.3241212
  -2.3241212 -2.3241212 -2.3241212 -2.3241212 -2.3241212 -2.3241212
  -2.3241212 -2.3241212 -2.3241212 -2.3241212 -2.3241212]
 [-2.3241212 -2.3241212 -2.3241212 -2.3241212 -2.3241212 -2.3241212
  -2.3241212 -2.3241212 -2.3241212 -2.3241212 -2.3241212 -2.3241212
  -2.3241212 -2.3241212 -2.3241212 -2.3241212 -2.3241212 -2.3241212
  -2.3241212 -2.3241212 -2.3241212 -2.3241212 -2.3241212]
 [-2.3241212 -2.3241212 -2.3241212 -2.3241212 -2.3241212 -2.3241212
  -2.3241212 -2.3241212 -2.3241212 -2.3241212 -2.3241212 -2.3241212
  -2.3241212 -2.3241212 -2.3241212 -2.3241212 -2.3241212 -2.3241212
  -2.32412

## 配列の要素を指定する

### インデックス（添え字）

In [74]:
a = np.arange(1, 20, 3)
print(a)

[ 1  4  7 10 13 16 19]


In [75]:
print(a[0])
print(a[1])

1
4


In [76]:
a[3] = 11
print(a)

[ 1  4  7 11 13 16 19]


* 2次元配列の場合

In [77]:
c = np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [78]:
print(c[0,0])

1


In [79]:
print(c[0,2])

3


In [80]:
print(c[1,0])

4


In [82]:
print(c[3,10])

IndexError: index 3 is out of bounds for axis 0 with size 2

## ndarrayを高速に扱う工夫
* 要素を個別に取り出して計算したりしない。

In [ ]:
import time
import numpy as np

x = np.ones(10000000)
y = np.ones(10000000)
s = np.zeros(10000000)
for _ in range(10):
  a = time.time()
  for i in range(10000000):
    s[i] = x[i] + y[i]
  b = time.time()
  print(b - a)

* 上のセルのように書くより、こう書くほうが良い

In [ ]:
import time
import numpy as np

x = np.ones(10000000)
y = np.ones(10000000)
s = np.zeros(10000000)
for _ in range(10):
  a = time.time()
  s = x + y
  b = time.time()
  print(b - a)

## スライシング
* 配列の要素をまとめて扱う。

In [83]:
a = np.arange(1, 20, 3)
print(a)

[ 1  4  7 10 13 16 19]


In [84]:
print(a[1:5])

[ 4  7 10 13]


In [85]:
print(a[0:6:2])

[ 1  7 13]


In [86]:
print(a[::-1])

[19 16 13 10  7  4  1]


In [87]:
print(a[-2::-1])

[16 13 10  7  4  1]


In [ ]:
print(a[-2:1:-1])

### fancy index

In [114]:
np.random.seed(1234)
a = np.random.randint(10, size=10)
print(a)

[3 6 5 4 8 9 1 7 9 6]


In [115]:
m = a % 3 == 0
print(m)

[ True  True False False False  True False False  True  True]


In [116]:
print(type(m))
print(m.dtype)

<class 'numpy.ndarray'>
bool


In [117]:
b = a[m]
print(b)

[3 6 9 9 6]


### where関数

In [100]:
#np.random.seed(1234)
a = np.random.randint(10,size=10)
print(a)

[3 1 3 7 1 7 4 0 5 1]


In [104]:
print(a > 3) # bool型の値が並んだ配列になる

[False False False  True False  True  True False  True False]


In [105]:
indices = a > 3
print(indices)

[False False False  True False  True  True False  True False]


In [108]:
print(a[1:4])

[1 3 7]


In [107]:
print(a[indices])

[7 7 4 5]


In [109]:
m = np.where(a % 2 == 0) #インデックスのtupleを返す
print(m)

(array([6, 7]),)


In [110]:
b = a[m]
print(b)

[4 0]


In [112]:
m = np.where(a > 3)
print(m)

(array([3, 5, 6, 8]),)


In [113]:
print(a[m])

[7 7 4 5]


In [118]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [119]:
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

In [120]:
b = []
for i in range(len(a)):
  if a[i] % 2 == 0:
    b.append(a[i])
b = np.array(b)
print(b)

[0 2 4 6 8]


In [121]:
np.random.seed(1234)
a = np.random.randint(10,size=10)
print(a)

[3 6 5 4 8 9 1 7 9 6]


In [122]:
m = np.where(a % 2 == 0, 'even', 'odd')
print(m)

['odd' 'even' 'odd' 'even' 'even' 'odd' 'odd' 'odd' 'odd' 'even']


In [ ]:
print(a[m == 'even'])

## 配列のコピー

### 配列のビュー
* 中身をコピーするわけではない。

In [ ]:
a = np.array([1, 2, 3])
b = a #ビューを作っている

### リストのコピー

In [ ]:
a = [1, 2, 3]
b = a
b[1] = 22
print(a)
print(b)

In [ ]:
c = a[:] #リストがコピーされる
c[2] = 234
print(a)
print(c)

### ndarrayの場合の`a[:]`
* コピーされるかどうか？

In [ ]:
a = np.array([1, 2, 3])
c = a[:]

In [ ]:
print(id(a) == id(c))

In [ ]:
c[1] = 22
print(a) #変化している

### `copy`メソッド

In [ ]:
a = np.array([1, 2, 3])
d = a.copy() #コピーを作る
print(id(a) == id(d))

In [ ]:
d[2] = 234
print(a) #変化していない

## 配列の形の変更

In [ ]:
a = np.arange(12)
print(a)

* NumPyのreshape関数

In [ ]:
b = np.reshape(a, (3, 4)) #
print(b)

* 元の配列の中身を変更してみる。

In [ ]:
a[3] = - a[3]
print(a)

* 注意: reshape関数は配列の中身をコピーしない。

In [ ]:
print(b) #中身が変化している!

* ndarrayのreshapeメソッド

In [ ]:
c = a.reshape((2,6))
print(c)

# 課題20250519
* 1から1000までの範囲のすべての偶数の和を求める計算を、NumPyの機能を使って書いてみよう。
  * NumPyの配列を使う、NumPyのarangeを使う、などなど。とにかく、何か一つでもNumPyの機能を使ってください。

In [123]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [125]:
print(np.sum(a))

45
