<a href="https://colab.research.google.com/github/tomonari-masada/course2025-intro2ml/blob/main/06_NumPy_2_%E6%8E%88%E6%A5%AD%E4%B8%AD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy入門 (2)
* ブロードキャスト
* 数学的なデータ処理
* 記述統計

In [1]:
import numpy as np

## ブロードキャスト

* 例1

In [6]:
aaa = np.array([1,2])
print(aaa)

[1 2]


In [7]:
aaa.shape

(2,)

In [2]:
a = np.array([[1, 2]])
print(a)

[[1 2]]


In [3]:
print(a.shape)

(1, 2)


In [8]:
b = np.array([3, 4])
print(b)

[3 4]


In [9]:
print(b.shape)

(2,)


In [10]:
c = a + b
print(c)

[[4 6]]


In [11]:
print(c.shape)

(1, 2)


* 例2

In [12]:
a = np.array([1,2])
print(a)

[1 2]


In [13]:
print(a.shape)

(2,)


In [14]:
b = np.array([[3,4],[2,3]])
print(b)

[[3 4]
 [2 3]]


In [15]:
print(b.shape)

(2, 2)


In [16]:
c = a + b
print(c)

[[4 6]
 [3 5]]


In [ ]:
print(c.shape)

* 例3

In [17]:
a = np.array([[1],[2],[3]])
print(a)

[[1]
 [2]
 [3]]


In [18]:
print(a.shape)

(3, 1)


In [19]:
b = np.array([[4,8],[5,10],[6,12]])
print(b)

[[ 4  8]
 [ 5 10]
 [ 6 12]]


In [20]:
print(b.shape)

(3, 2)


In [22]:
c = a * b
print(c)

[[ 4  8]
 [10 20]
 [18 36]]


* 例4

In [23]:
a = np.array([1,2])
print(a)

[1 2]


In [24]:
print(a.shape)

(2,)


In [25]:
b = np.array([[3],[4]])
print(b)

[[3]
 [4]]


In [26]:
print(b.shape)

(2, 1)


In [29]:
c = a + b
print(c) # 出力がなぜそうなるか説明してみよう

[[4 5]
 [5 6]]


In [ ]:
print(c.shape)

## 数学的なデータ処理

* 様々な関数

In [30]:
print(np.power(2, 3))
print(np.power(2.1, 2.8))

8
7.983880450340076


In [31]:
a = np.arange(1, 11)
print(np.sqrt(a))
print(np.arctan(a))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
[0.78539816 1.10714872 1.24904577 1.32581766 1.37340077 1.40564765
 1.42889927 1.44644133 1.46013911 1.47112767]


In [32]:
x = np.linspace(-1, 1, 11)
print(x)
print(np.exp(x))

[-1.  -0.8 -0.6 -0.4 -0.2  0.   0.2  0.4  0.6  0.8  1. ]
[0.36787944 0.44932896 0.54881164 0.67032005 0.81873075 1.
 1.22140276 1.4918247  1.8221188  2.22554093 2.71828183]


## 記述統計
* グラフの描き方は別のnotebookで。
  * matplotlibという可視化ライブラリを使う。

In [33]:
x = np.random.randn(3, 10)
x = x * 3 + 5
print(x)

[[ 3.62753984 -1.73730132  4.17999213  1.62565267  2.13662337  4.72921067
   0.29659401  5.04730075  1.23675307  2.41464587]
 [ 5.65804852  2.26436872  2.918113    4.90647198  1.86087287  7.69648924
   9.70987266  1.40010123  4.15355597  8.76858206]
 [ 6.84986837 10.19393842  8.37999144  5.21590976  9.10926253  1.88327044
   1.76213489  6.27859638 10.346847    6.75686533]]


In [34]:
print(np.mean(x))

4.655672394746865


In [35]:
print(np.mean(x, axis=0))

[5.37848558 3.5736686  5.15936552 3.91601147 4.36891959 4.76965678
 3.92286718 4.24199945 5.24571868 5.98003108]


In [36]:
print(np.mean(x, axis=1))

[2.35570111 4.93364762 6.67766846]


In [37]:
print(np.median(x), np.var(x), np.std(x))

4.454601401696513 9.957631116494662 3.1555714405626536


In [38]:
x = np.random.randn(2, 100)
print(x)
print(np.cov(x[0], x[1]))
print(np.corrcoef(x[0], x[1]))

[[-1.35686978e+00 -2.55762582e-01 -3.69545463e-02  1.75131186e+00
   7.99400754e-01  2.15217406e+00  2.11543827e-01  8.74063239e-01
   1.31761424e+00  2.21032986e-02  7.32023913e-01  7.21802055e-01
   6.49883996e-02 -2.69899888e-01 -7.60642740e-01 -7.34107876e-01
  -1.15029449e+00 -6.05347702e-01  7.50109946e-02  1.14711323e+00
  -9.41322972e-02  4.36736219e-01  1.70675124e+00 -6.69416649e-01
  -7.18934365e-01  8.92764953e-01  5.49684628e-01  4.53903863e-01
   2.12237667e+00  1.48903315e+00 -1.19848117e+00  5.07342253e-01
   1.06721652e+00 -3.03949881e-02  1.92658694e+00 -2.63812645e-01
  -2.00382442e+00  6.18944857e-01  3.79070484e-01  9.11676634e-01
  -1.57499297e-01 -8.96765804e-02  2.65712504e-01  5.59055853e-01
   4.67367275e-01  6.27010699e-02 -1.01140376e+00  1.14787104e+00
   7.67291692e-01  1.57112262e-01 -2.59500980e-02 -9.34701318e-02
   1.02754487e+00  3.18453176e-01 -1.66426249e+00 -1.22573324e+00
   2.64942024e+00 -3.28463793e-01 -5.39287487e-01  1.11132371e-01
   4.81602

## NumPyの練習
* NumPyに実装されたさまざまな機能について、全てを授業で説明することはできません・・・。

In [ ]:
x = np.zeros(10)
print(x)

In [ ]:
x = np.arange(10, 50)
print(x)

In [ ]:
x = np.arange(50)
x = x[::-1]
print(x)

In [ ]:
Z = np.arange(9).reshape(3, 3)
print(Z)

In [ ]:
x = np.array([1, 2, 0, 0, 4, 0])
nz = np.nonzero(x)
print(nz)
print(x[nz])

In [ ]:
Z = np.eye(3)
print(Z)

In [ ]:
Z = np.eye(3)
nz = np.nonzero(Z)
print(nz)
print(Z[nz])

In [ ]:
Z = np.random.random((10, 10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

In [ ]:
x = np.random.random(30)
m = x.mean()
print(m)

In [ ]:
Z = np.arange(10)
np.sum(Z)

## NaN
* NaNとはnot a numberで、非数のこと。

In [39]:
print(0.0 / np.ones(5))

[0. 0. 0. 0. 0.]


In [40]:
print(0.0 / np.zeros(5))

[nan nan nan nan nan]


<ipython-input-40-5c465b4f478f>:1: RuntimeWarning: invalid value encountered in divide
  print(0.0 / np.zeros(5))


In [ ]:
print(0 * np.nan)

In [ ]:
print(np.nan - np.nan)

* nanと比較する場合、相手がどんな値でも
  * <, >, ==, <=, >=は常にFalse
  * !=は常にTrue

In [ ]:
print(np.nan == np.nan)

In [ ]:
print(np.nan != np.nan)

## inf
* 無限大のこと。

In [41]:
print(np.inf)

inf


In [44]:
print(1e-3)

0.001


In [42]:
print(1e15)

1000000000000000.0


In [43]:
print(np.inf > 1e15)

True


In [45]:
print(np.inf > np.nan)

False


* NumPyを使ったコードを動かしていて、途中の計算結果がNaNやinfになったら、何か変なことが起きている、ということ。

## 注意: 浮動小数点数の特徴
* これはPython全体での話です。
  * NumPyに限った話ではありません。
  * Pythonで数値計算をする場合の一般的な注意事項です。
* 一言で言えば、計算機は実数を完全に厳密には表現できないです。

In [46]:
print(0.3 == 3 * 0.1)
print(0.3 == 2 * 0.15)

False
True


In [47]:
print(3 * 0.1)

0.30000000000000004


In [48]:
import numpy as np
a = np.array([0.3])

In [49]:
print(a)

[0.3]


In [50]:
b = np.array([3 * 0.1])
print(b)

[0.3]


In [51]:
print(a - b)

[-5.55111512e-17]


In [ ]:
b = np.array([2 * 0.15])
print(a - b)